pipeline {
    agent any

    stages {
        stage('Maven package') {
            agent {
                docker {
                    image 'maven:3.9.11-eclipse-temurin-21'
                    args '''
                        -v $HOME/.m2:/root/.m2:z
                        -u root
                        --network devops
                    '''
                    reuseNode true // Sans ça, il y aura un 2eme workspace
                }
            }

            steps {
                dir('Super-heros/Super-heros') {
                    withSonarQubeEnv('SonarQube') {
                        sh "mvn clean verify sonar:sonar -Dsonar.projectKey=super-heros-boot -Dsonar.projectName='super-heros-boot'"
                    }
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Super-heros/Super-heros') {
                    sh 'docker build -t superheros:boot .'
                }
            }
        }

        // stage('Docker Deploy') {
        //     steps {
        //         dir('DOCKER/commandes/compose/quest') {
        //             sh 'docker compose up -d --no-deps --build boot'
        //         }
        //     }
        // }
    }
}
